version: '3.1'
services:

  oauth-server:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth-server
    networks:
      - hmpps
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  prison-api:
    image: quay.io/hmpps/elite2-api:latest
    container_name: prison-api
    depends_on:
      - localstack
    networks:
      - hmpps
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb-localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    networks:
      - hmpps
    ports:
      - "4567-4597:4567-4597"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
