version: '3.1'
services:
  oauth-server:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth-server
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    container_name: prison-api
    depends_on:
      - oauth-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
