# ===================================================================
# Standard Spring Boot configuration
# ===================================================================

spring:

  datasource:
    continueOnError: true
    initialize: false

    hikari:
      pool-name: Elite2-CP
      connectionTimeout: 1000
      validationTimeout:  500

  jersey:
    type: filter


logging:
  level:
    org.springframework.security: INFO

    
  messages:
    cache-seconds: 1

server:
  servlet:
    context-path: /
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto