spring:
  datasource:
    url: jdbc:hsqldb:mem:nomis-db;sql.syntax_ora=true;get_column_name=false;shutdown=false;sql.nulls_first=false;sql.nulls_order=false
    username: sa
    password:

    hikari:
      maximum-pool-size: 2

  flyway:
    enabled: true
    locations: classpath:/db/migration/nomis/ddl,classpath:/db/migration/data,classpath:/db/migration/nomis/data,classpath:/db/migration/nomis/data-hsqldb

  profiles:
    include: dev

data.compliance:

  db:
    enable.parallel.hints: false

  outbound.referral:
    sqs:
      provider: localstack
      queue.name: outbound_referral_queue
      queue.url: http://localstack:4576/queue/outbound_referral_queue
      dlq.name: outbound_referral_dead_letter_queue
      endpoint.url: http://localstack:4576
      region: eu-west-2

  inbound.deletion:
    sqs:
      provider: localstack
      queue.name: inbound_deletion_queue
      dlq.name: inbound_deletion_dead_letter_queue
      endpoint.url: http://localstack:4576
      region: eu-west-2

graceful:
  shutdown:
    enabled: false
