server:
  port: 8070

spring:
  application:
    name: elite2-api

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          fetch_size: 100

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/issuer
          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms

api:
  base:
    path: /api