server:
  servlet:
    context-path: /elite2api
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  profiles:
#    include: nomis-local,logstash,ai
    include: nomis-local,ai

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  datasource:
    hikari:
      maximum-pool-size: 10
      connectionTimeout: 1000
      validationTimeout:  500

  replica:
    datasource:
      hikari:
        maximum-pool-size: 10
        connectionTimeout: 1000
        validationTimeout:  500

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.endpoint.url}/.well-known/jwks.json
