defaults: &defaults
  working_directory: ~/app
  environment:
    JAVA_TOOL_OPTIONS: -Xmx1024m -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

version: 2.1

orbs:
  owasp: entur/owasp@0.0.6

executors:
  builder:
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-jdk-browsers

  deployer:
    <<: *defaults
    docker:
      - image: circleci/python:latest-browsers

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle
            - Dockerfile
            - run.sh
            - AI-Agent.xml

  build_docker:
    executor: deployer
    steps:
      - setup_remote_docker:
          exclusive: true
      - attach_workspace:
          at: ~/app
      - run:
          name: Build container and publish to docker hub
          command: |
            jar xvf build/libs/elite2-api-*.jar BOOT-INF/classes/META-INF/build-info.properties
            API_VERSION=$(grep 'build.version=' BOOT-INF/classes/META-INF/build-info.properties | awk -F= '{print $2}')
            rm BOOT-INF/classes/META-INF/build-info.properties

            # build the container
            docker build --rm=false . \
               --tag "mojdigitalstudio/elite2-api:$API_VERSION" \
               --label "maintainer=feedback@digital.justice.gov.uk" \
               --label "app.version=$API_VERSION" \
               --label "build.version=$API_VERSION" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$CIRCLE_SHA1"

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mojdigitalstudio/elite2-api:$API_VERSION
            docker tag mojdigitalstudio/elite2-api:$API_VERSION mojdigitalstudio/elite2-api:latest
            docker push mojdigitalstudio/elite2-api:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - nomis-api

  scheduled:
    triggers:
      - schedule:
          cron: "10 11 * * 1-5"
          filters:
            branches:
              only:
                - master
                - DT-393-add-owasp
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: builder
