defaults: &defaults
  working_directory: ~/app

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: sysconjusticesystems/ci-java-node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build aggregate --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: elite2-api-impl/build/test-results
      - store_test_results:
          path: elite2-api-impl/target/site
      - store_artifacts:
          path: elite2-api-impl/build/libs
      - store_artifacts:
          path: elite2-api-impl/build/reports/tests
      - store_artifacts:
          path: elite2-api-impl/build/reports/jacoco
      - store_artifacts:
          path: elite2-api-impl/target/site
      - store_artifacts:
          path: elite2-api/raml/api.html
      - persist_to_workspace:
          root: .
          paths:
            - elite2-api-impl/build/libs
            - build.gradle
            - Dockerfile
            - run.sh

  build_docker:
    <<: *defaults
    docker:
      - image: circleci/python:latest-browsers
    steps:
      - setup_remote_docker:
          exclusive: true
      - attach_workspace:
          at: ~/app
      - run:
          name: Build container and publish to docker hub
          command: |
             jar xvf elite2-api-impl/build/libs/elite2-api-impl-*.jar META-INF/build-info.properties
             API_VERSION=$(grep 'build.version=' META-INF/build-info.properties | awk -F= '{print $2}')
             rm META-INF/build-info.properties
             TAG=${API_VERSION}.${CIRCLE_BRANCH}
             if [[ "${CIRCLE_BRANCH}" == "nomis-api" ]]; then
               TAG=ELITE2_API_${API_VERSION}
             fi
             docker build --rm=false . \
                --tag "mojdigitalstudio/elite2-api:$TAG" \
                --label "maintainer=michael.willis@digital.justice.gov.uk" \
                --label "app.version=$TAG" \
                --label "build.version=$TAG" \
                --label "build.number=$CIRCLE_BUILD_NUM" \
                --label "build.url=$CIRCLE_BUILD_URL" \
                --label "build.gitref=$CIRCLE_SHA1"
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker push mojdigitalstudio/elite2-api:$TAG

             if [[ "${CIRCLE_BRANCH}" == "nomis-api" ]]; then
              docker tag mojdigitalstudio/elite2-api:$TAG mojdigitalstudio/elite2-api:latest
              docker tag mojdigitalstudio/elite2-api:$TAG sysconjusticesystems/elite2-api:latest
              docker push mojdigitalstudio/elite2-api:latest
              docker push sysconjusticesystems/elite2-api:latest
             fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only: nomis-api