version: 2.1
parameters:
  image_name:
    type: string
    default: "quay.io/hmpps/elite2-api"
  app_name:
    type: string
    default: "elite2-api"

orbs:
  dps: ministryofjustice/dps@1.1.1
  owasp: entur/owasp@0.0.6

defaults: &defaults

executors:
  builder:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/app
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - build/libs
      #       - build.gradle
      #       - Dockerfile
      #       - run.sh
      #       - AI-Agent.xml

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - dps/build_docker:
          name: build_docker
          image_name: << pipeline.parameters.image_name >>
          filters:
            branches:
              only:
                - test_k8s_deploy
      - dps/deploy_env:
          name: deploy_dev
          env: "dev"
          app_name: << pipeline.parameters.app_name >>
          filters:
            branches:
              only:
                - test_k8s_deploy
          requires:
            - build_docker
            - build

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: builder
