version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0
  owasp: entur/owasp@0.0.6

defaults: &defaults

executors:
  builder:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/app
    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - build/libs
      #       - build.gradle
      #       - Dockerfile
      #       - run.sh
      #       - AI-Agent.xml

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - master
      - hmpps/deploy_env:
          name: deploy_dev
          env: "t3"
          filters:
            branches:
              only:
                - master
          requires:
            - build_docker
            - build
      - request-stage-approval:
          type: approval
          requires:
            - deploy_dev

      - hmpps/deploy_env:
          name: deploy_stage
          env: "t2"
          context: elite2-api-t2
          requires:
            - request-stage-approval
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_stage

      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: elite2-api-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod

      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          context: elite2-api-prod
          requires:
            - request-prod-approval
  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: builder
