version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@dev:alpha4
  owasp: entur/owasp@0.0.10

defaults: &defaults

executors:
  builder:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/app
    environment:
      _JAVA_OPTIONS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-XX:+UseContainerSupport
jobs:
  check:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew check --exclude-task testIntegration --exclude-task testWithSchemaNomis
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs
  test-integration:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew testIntegration
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs
  test-schema-nomis:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew testWithSchemaNomis
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_test_results:
          path: build/test-results
      - store_test_results:
          path: build/serenity
      - store_artifacts:
          path: build/libs

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - POC-generic-service-chart
      - hmpps/deploy_env:
          name: deploy_dev
          env: "t2"
          context: prison-api-t2
          filters:
            branches:
              only:
                - POC-generic-service-chart
          requires:
            - build_docker
