# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: quay.io/hmpps/elite2-api
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080
