# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/prison-api
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080

env:
  DATA_COMPLIANCE_DELETION_ENABLED: true
